version: '3.7'

services:
  logging-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logging-service
    ports:
      - "8000:8000"  # Expose FastAPI service to the host
    networks:
      - log-network
    volumes:
      - ./app:/app  # Optional: Mount the app folder for live updates during development

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # Expose Loki to the host
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - log-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log  # Adjust based on where FastAPI writes logs
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - log-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana to the host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - log-network

networks:
  log-network:
    driver: bridge
