server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Monitor FastAPI container logs
  - job_name: logging-service
    static_configs:
      - targets:
          - localhost  # Not used, required placeholder
        labels:
          job: logging-service
          __path__: /var/log/*.log
